### ISSUE TITLE
chebfun_v4/@chebop/pde15s.m unable to call

### ISSUE THREAD

**Issue by xiaoli12543** [chebfun/chebfun_v4#1]
Hello, the unew variable in line 509 of this file(chebfun_v4/@chebop/pde15s.m) is not defined. May I know how to solve it? I would like to use this function, but I am not familiar with the relevant theory. I hope to receive your answer.

**Comment by nickhale** [comment]
chebfun_v4 is no longer maintained or supported.

Please try using the current release: https://github.com/chebfun/chebfun

N
